# -*- coding: utf-8 -*-
"""PDF_To_Text_Conversion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZqhON1tbfKmgMGqER7TmKUY5LAL1xQHS
"""

# created by Amna Dridi on 02 Feb 2023
pip install pdfminer.six

from pdfminer.high_level import extract_text
chapter = 'Approved_Document_A-Content2'
text = extract_text(chapter+'.pdf')
textfile=open(r'Text-'+chapter+'.txt',"a")
textfile.writelines(text)
textfile.close()